# Generated by Django 5.2.6 on 2025-09-13 15:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('license_number', models.TextField(unique=True)),
                ('current_cycle_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.TextField()),
                ('pickup_location', models.TextField()),
                ('dropoff_location', models.TextField()),
                ('estimated_weight', models.IntegerField(default=80000)),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_duration', models.IntegerField(blank=True, null=True)),
                ('route_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, to='trucking.driver')),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='HosViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('driving_limit', 'Driving Limit'), ('duty_limit', 'Duty Limit'), ('break_required', 'Break Required')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('violation', 'Violation')], default='warning', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, to='trucking.driver')),
                ('trip', models.ForeignKey(blank=True, db_column='trip_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trucking.trip')),
            ],
            options={
                'db_table': 'hos_violations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EldLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateTimeField()),
                ('total_miles', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('driving_time', models.IntegerField(default=0)),
                ('on_duty_time', models.IntegerField(default=0)),
                ('off_duty_time', models.IntegerField(default=0)),
                ('sleeper_berth_time', models.IntegerField(default=0)),
                ('time_entries', models.JSONField()),
                ('remarks', models.TextField(blank=True)),
                ('is_compliant', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, to='trucking.driver')),
                ('trip', models.ForeignKey(blank=True, db_column='trip_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trucking.trip')),
            ],
            options={
                'db_table': 'eld_logs',
                'ordering': ['-log_date'],
            },
        ),
    ]
